#   This file is part of Invoke-AntivM.
#
#   Copyright 2019 Paolo Di Prodi <@robomotic>
#         while at Fortinet <http://www.fortiguard.com>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.



#
# Module manifest for module 'Invoke-AntiVM'
#
# Generated by: Paolo Di Prodi (@robomotic) and Fred Gutierrez (@macheyael)
#
# Generated on: 2019-07-23
#



@{

# Version number of this module.
ModuleVersion = '1.1'

# ID used to uniquely identify this module
GUID = 'd2d296bc-f75c-4806-8ac2-dd8011029b66'

# Author of this module
Author = 'Paolo Di Prodi (@robomotic) and Fred Gutierrez (@macheyael)'

# Copyright statement for this module
Copyright = 'Apache License, Version 2.0'

# Description of the functionality provided by this module
Description = 'PowerShell module file for importing all required modules for the Invoke-AntiVM framework.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = '2.0'

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @('Invoke-AntiVM.ps1','Invoke-AntiVM-Programs.ps1','Invoke-AntiVM-CPU.ps1','Invoke-AntiVM-Network.ps1')

# Functions to export from this module
FunctionsToExport = '*'

# HelpInfo URI of this module
# HelpInfoURI = ''

}